Repository shophubkr/shophub-server, pull requests merged in 2023-10, with the labels that each got.

#22 #20 - 소셜 로그인 구현
  .github/workflows/ci.yml
  .gitignore
  build.gradle.kts
  src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
  src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/CustomOAuth2User.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/OAuthAttributes.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/handler/OAuth2LoginFailureHandler.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/handler/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/service/CustomOAuth2UserService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/userInfo/GoogleOAuth2UserInfo.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/userInfo/KakaoOAuth2UserInfo.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/userInfo/NaverOAuth2UserInfo.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/userInfo/NoSocialOAuth2USerInfo.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/userInfo/OAuth2UserInfo.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/util/PasswordUtil.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/AuthController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/domain/ProviderType.kt
  src/main/kotlin/kr/co/shophub/shophub/user/domain/User.kt
  src/main/kotlin/kr/co/shophub/shophub/user/domain/UserRole.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/JoinRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/LoginRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/SocialJoinRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/SocialJoinResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/TokenRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/TokenResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/UserResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/ProviderType.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/User.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/UserRole.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
  src/main/resources/application.yml
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/AuthServiceTest.kt
  src/test/resources/application.yml
Labels: 😎 Feature, ✋ Help wanted

#23 #15 - 상품 API 기능
  src/main/kotlin/kr/co/shophub/shophub/global/file/FileExtension.kt
  src/main/kotlin/kr/co/shophub/shophub/global/file/controller/FileController.kt
  src/main/kotlin/kr/co/shophub/shophub/global/file/dto/UploadFileRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/global/file/dto/UploadFileResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/global/file/service/FileService.kt
  src/main/kotlin/kr/co/shophub/shophub/product/controller/ProductController.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/CreateProductRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductIdResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductImagesResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductListResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/UpdateProductRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/product/model/category/ProductCategory.kt
  src/main/kotlin/kr/co/shophub/shophub/product/model/category/ProductDetailCategory.kt
  src/main/kotlin/kr/co/shophub/shophub/product/model/image/ProductImage.kt
  src/main/kotlin/kr/co/shophub/shophub/product/model/product/Product.kt
  src/main/kotlin/kr/co/shophub/shophub/product/model/product/ProductStatus.kt
  src/main/kotlin/kr/co/shophub/shophub/product/model/tag/ProductTag.kt
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductCategoryRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductImageRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductTagRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/model/Shop.kt
  src/test/kotlin/kr/co/shophub/shophub/product/service/ProductServiceTest.kt
Labels: 🧹Clean up, 😎 Feature, 🛠️ Refactoring

#29 #26 - 유저 도메인 개발
  build.gradle.kts
  src/main/kotlin/kr/co/shophub/shophub/global/event/EventListener.kt
  src/main/kotlin/kr/co/shophub/shophub/global/event/JoinEvent.kt
  src/main/kotlin/kr/co/shophub/shophub/global/exception/ExceptionUtil.kt
  src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/AuthController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/InfoUpdateRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/MailRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/MyPageResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/PasswordRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/PasswordUpdateRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/User.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/MailService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/AuthServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/UserServiceTest.kt
Labels: 😎 Feature

#30 #27 - 매장 팔로우 구현
  src/main/kotlin/kr/co/shophub/shophub/follow/controller/FollowController.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/dto/FollowPageResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/model/Follow.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/repository/FollowRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/service/FollowService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/exception/ExceptionUtil.kt
  src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/model/Shop.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
  src/test/kotlin/kr/co/shophub/shophub/follow/service/FollowServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/UserServiceTest.kt
Labels: 😎 Feature

#31 #28 - 쿠폰 API 기능 개발
  build.gradle.kts
  src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CouponIdResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CouponListResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CouponResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CreateCouponRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/model/Coupon.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/config/QueryDslConfig.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductListResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/model/Shop.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/UserCouponIdResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/UserCouponListResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/UserCouponResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/User.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/UserCoupon.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/UserCouponCond.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepositoryImpl.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
  src/main/resources/application-local.yml
  src/test/kotlin/kr/co/shophub/shophub/coupon/service/CouponServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/UserServiceTest.kt
Labels: 😎 Feature

#33 #32 - 사업자 관련 API 구현
  src/main/kotlin/kr/co/shophub/shophub/business/model/Business.kt
  src/main/kotlin/kr/co/shophub/shophub/business/repository/BusinessRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/handler/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/dto/CreateShopRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/model/Shop.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/service/ShopService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/JoinRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/User.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/UserRole.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
  src/test/kotlin/kr/co/shophub/shophub/coupon/service/CouponServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/follow/service/FollowServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/product/service/ProductServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/shop/service/ShopServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/AuthServiceTest.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/UserServiceTest.kt
Labels: 😎 Feature, 🛠️ Refactoring

#34 #24 - 검색 기능 개발
  build.gradle.kts
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductTagRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductTagRepositoryCustom.kt
  src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductTagRepositoryImpl.kt
  src/main/kotlin/kr/co/shophub/shophub/search/controller/SearchController.kt
  src/main/kotlin/kr/co/shophub/shophub/search/service/SearchService.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/dto/ShopListResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/repository/ShopTagRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/repository/ShopTagRepositoryCustom.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/repository/ShopTagRepositoryImpl.kt
Labels: 😎 Feature
