Repository shophubkr/shophub-server, pull requests merged in 2023-11, with the labels that each got.

#40 #36 - 코드 리팩토링
  src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/controller/FollowController.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/service/FollowService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/kr/co/shophub/shophub/test/TestController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/AuthController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
Labels: 🛠️ Refactoring

#39 #38 - EC2 서버 다운 문제 / 브랜치 선택 배포
  .github/workflows/cd-dev.yml
  src/main/resources/application-local.yml
Labels: 🐛 bug, 🛠️ Refactoring

#42 #41 - CORS 설정 추가
  src/main/kotlin/kr/co/shophub/shophub/global/HealthController.kt
  src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
  src/main/kotlin/kr/co/shophub/shophub/global/config/WebConfig.kt
Labels: 🐛 bug, 😎 Feature

#44 #43 - 회원 정보 수정 관련 API
  src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/NicknameRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/user/dto/SimpleInfoResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/AuthServiceTest.kt
Labels: 😎 Feature
