Repository shophubkr/shophub-server, pull requests merged in 2024-01, with the labels that each got.

#49 #48 - 상품, 쿠폰 response 필드 추가
  src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CouponResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CreateCouponRequest.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/model/Coupon.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
  src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/repository/ShopRepository.kt
  src/test/kotlin/kr/co/shophub/shophub/coupon/service/CouponServiceTest.kt
Labels: 😎 Feature

#51 #50 - 팔로우한 매장 정렬 조건 및 검색 조건 추가
  src/main/kotlin/kr/co/shophub/shophub/follow/controller/FollowController.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/dto/SortCondition.kt
  src/main/kotlin/kr/co/shophub/shophub/follow/service/FollowService.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/dto/ShopSimpleResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
Labels: 😎 Feature

#55 #54 - 이메일 인증 관련 코드 제거
  src/main/kotlin/kr/co/shophub/shophub/global/config/S3Config.kt
  src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
  src/main/kotlin/kr/co/shophub/shophub/global/event/EventListener.kt
  src/main/kotlin/kr/co/shophub/shophub/global/event/JoinEvent.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/OAuthAttributes.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/handler/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/service/CustomOAuth2UserService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/oauth/userInfo/KakaoOAuth2UserInfo.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/AuthController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/ProviderType.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/User.kt
  src/main/kotlin/kr/co/shophub/shophub/user/model/UserRole.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/MailService.kt
  src/test/kotlin/kr/co/shophub/shophub/user/serivce/AuthServiceTest.kt
Labels: 🛠️ Refactoring

#56 #53 - 스케줄러를 통해 매일 자정 쿠폰 만료 업데이트 // 쿠폰 조회 쿼리 개선
  src/main/kotlin/kr/co/shophub/shophub/ShopHubApplication.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/CouponResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/model/Coupon.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepositoryCustom.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepositoryImpl.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
  src/main/kotlin/kr/co/shophub/shophub/global/config/TimeConfig.kt
  src/main/kotlin/kr/co/shophub/shophub/shop/model/Shop.kt
  src/main/kotlin/kr/co/shophub/shophub/test/TestController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepository.kt
  src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepositoryImpl.kt
  src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
  src/test/kotlin/kr/co/shophub/shophub/coupon/service/CouponServiceTest.kt
Labels: 😎 Feature, 🛠️ Refactoring

#59 #58 - 만료가 가장 임박한 쿠폰 조회
  src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/dto/ShortestExpirationCouponResponse.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepositoryCustom.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepositoryImpl.kt
  src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
  src/test/kotlin/kr/co/shophub/shophub/coupon/service/CouponServiceTest.kt
Labels: 😎 Feature
